### PR TITLE
Split timer update 0912

### PR DESCRIPTION
**Pull request by ethomas997**
Ignore split time before lap 0 crossing.

Added more stats to Cluster display.

Fixed 'split_id' assignment.

Checking timeDiff at each heartbeat/query and using median value.

If reached timeout and never connected then stop trying

If never connected then don't attempt reconnects while race in progress

If never connected then don't warn on failed emits to slave

If race in progress when reconnected then resend race-start emit.

On GUI cluster status should say "never connected" if disconnects==0 and "connection lost" is disconnects>0.

If running as slave timer and missed stop/discard msg then stop/clear current race at start.

Do ClusterNodeSet status log at race stop.

Ignore split pass record if race not running.

Don't show split-times field-slots on GUI if slaves never connected.

Move up assignment of PROGRAM_START_MTONIC.

Added audio checkbox for 'Cluster Timer Connect / Disconnect'.

Changed name of cluster mode option from 'timer' to 'split'.

Don't keep logging attempting-to-connect messages if slave never available.

Substitute asterisks in given address with values from host IP.

Check program version on cluster timer.

Added cluster 'queryInterval' config option.

Added util Averager class.

Implemented real support for cluster 'mirror' timer.

Added cluster 'recEventsFlag' config parameter.

Only show lap rows for split times if split timers connected.

Show timer mode in status info: M or S after address.

### CODE REVIEW

**Comment by pulquero** [comment]
Why use the median? I would have thought the mean makes the most sense (generally the case when you have a sample of measurements with a guassian distribution).

**Comment by ethomas997** [comment]
At that point we're trying to determine the time difference between the two timer clocks.  If there's an unusually large or small value because of a transient network issue, we want to ignore it rather than have it pull the mean too much.

**Comment by HazardCreative** [comment]
I haven't walked through all of this code yet, but is this checking and adjusting the time difference every time they communicate? The browser sync polls the server until it can make a very good guess as to the difference, and then just uses that value as the clock offsets. This does assume the clocks tick at the same rate, but the clock used by the pi and the browser don't differ enough. If clock drift is a concern, maybe a hybrid strategy should be used that redetermines the offset every few minutes?

I agree with using the median. High outliers definitely occur in this type of measurement (especially when WiFi is involved) and should be ignored rather than incorporated. However, outliers on the low side offer unique opportunity to hone in on the correct offset. One strategy used by the browser/pi sync is to favor samples with lower transport times by discarding samples that are newly determined to be outside the possible sync range. Perhaps that could apply here as well? https://github.com/RotorHazard/RotorHazard/blob/master/src/server/templates/race.html#L68-L79

**Comment by pulquero** [comment]
Large and small values cancel each other out - the mean is the best estimator. Though more to the point is that it is non-guassian as minimal measurable value is bounded by zero. Poisson is probably more apt.

Before we embark too deeply down the path of implementing our own distributed time-synchronisation system, can we not make good use of prior art like PTP or a python implementation of lamport clocks or something?

**Comment by ethomas997** [comment]
You guys are way over-thinking this.  The main job of that part of the code is to verify that the clocks are in sync, and it does that just fine.  If the clocks are significantly out of sync then it attempts to correct it, but that's just a bit of added-value functionality.  If the operator is serious about getting cross-timer accuracy then they need to synchronize the clocks via RTC modules or NTP.

**Comment by pulquero** [comment]
Noted, I guess where I was coming from is if we have the same sort of problem popping up in various places whether we should try to solve it strategically across the board rather than ad-hoc? And maybe this is more of a question of where we want to go rather than what to do now.

**Pull request merged**
