### PR TITLE
Update doc on PCB for 6 arduinos

### PR DESCRIPTION
**Pull request by laurent-clouet**

### CODE REVIEW

**Comment by ethomas997** [comment]
@Aaronsss Could you do a review of this PR?

**Comment by ethomas997** [comment]
@Aaronsss Sorry I was thinking this was referring to your 6-node STM32 PCB; my mistake

**Comment by ethomas997** [comment]
@szafranski Could you review this PR?

**Comment by szafranski** [comment]
Will happily do that :)

**Review by szafranski — APPROVED** [review]

**Pull request merged**
