### PR TITLE
Android scanner app

### PR DESCRIPTION
**Pull request by pulquero**

### CODE REVIEW

**Comment by ethomas997** [comment]
Can you post an '.apk' file for the app?

**Comment by pulquero** [comment]
[app-debug.zip](https://github.com/RotorHazard/RotorHazard/files/4050556/app-debug.zip)

**Comment by HazardCreative** [comment]
What benefits does an installed app have over an improved web interface?

**Comment by pulquero** [comment]
It provides a simple diagnostic interface - just connect your phone straight to the nano.
You can also use it as a standalone scanner/vrx with a simple piece of hardware (nano+rx).

**Comment by HazardCreative** [comment]
Thanks for the extra information.

**Comment by ethomas997** [comment]
The app starts up with the soft keyboard showing -- is there a value it's looking to have entered?  I got it to work with a simple Arduino + RX5808 dongle; nice basic band scanner.

**Comment by HazardCreative** [comment]
This probably makes sense in a separate repository under the RotorHazard org. I can get that set up. Anything in particular that you'd like to name it?

**Comment by pulquero** [comment]
Repo name suggestion: RotorHazard-android

**Comment by HazardCreative** [comment]
Open for business at https://github.com/RotorHazard/RotorHazard-android/ . You have full access to maintain as you see fit.

**Comment by pulquero** [comment]
Moved to new repo.

**Pull request closed without merging**
