### PR TITLE
add beep on first pass issue #14

### PR DESCRIPTION
**Pull request by Klaus-Michael**
implemented a beep on first pass.

### CODE REVIEW

**Comment by ethomas997** [comment]
Thanks for the PR; the functionality sounds good.  We should test how it works when the EnterAt/ExitAt beeps are also enabled.  Some minor notes:

Phonetic data refers to spoken-voice prompts, so the 'phonetic_data_first_pass' function in 'race.html' should be named something more like "play_first_pass_beep".

The coding style in 'race.html' uses tabs, so your new added lines should also use tabs for indentation (not spaces).

**Comment by ethomas997** [comment]
Thinking about this some more, it seems like what your looking for is to have the system play the ExitAt beeps, but only on the initial (lap 0) pass, yes?  I'd say that, rather than adding a new type of tone, the "On First Pass" option should make it play the same EnterAt/ExitAt tones, but only on the initial (lap 0) pass.

**Comment by HazardCreative** [comment]
The exit emit doesn't know what lap is being recorded, or even if a lap is being recorded at all—so getting that data in at that point could be complicated and slow down the system in other ways. I'm fine with a more generic "first pass registered" hook, that would could potentially tie other behaviors to if we wanted down the road. (Maybe something to do with drag racing?)

Simply avoid playing the tone if 'exit beep' is on, so they're not doubled up. Note that this method won't beep on first pass if 'exit beep' is on and the pass is marked via the manual lap button. I think that's okay, as the intent of this is to know whether the pass registered. If you're pressing the manual button, you already have this information (it hasn't registered yet).

Any other edits here? I think it's looking pretty good—but I don't have a quad with me so I won't merge in until a little more testing has been done.

**Comment by Klaus-Michael** [comment]
sounds good to me.

**Pull request merged**
