### PR TITLE
Fix bug in serial_node introduced in PR #287

### PR DESCRIPTION
**Pull request by deets**

### CODE REVIEW

**Comment by HazardCreative** [comment]
It's now possible to access the config by importing it. Is it better to switch to that method instead of continuing to pass it in? For example: https://github.com/RotorHazard/RotorHazard/blob/master/src/server/led_handler_bitmap.py

**Comment by deets** [comment]
My personal bias here is pretty clear: that treats it as a global variable. And I don't like global variables. However this is your project, and if that's the style you want things to happen, that's your call. The change would then go *much* deeper though that I feel comfortable with - it would mean removing config as argument from all the different setups, and that would need thorough testing. As we see right now ;)

**Comment by HazardCreative** [comment]
The restructure is being undertaken to solve accessing data across modules. As I understand it, I've moved to the method recommended by Python: https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules

However, I'm not a professional back-end developer and am interested in hearing about best practices.

**Comment by deets** [comment]
Technically this is correct, but I think it conflates a valid use-case (share immutable state, and the odd singleton) with a general principle of how data should flow. A global variable is a global variable, and these are problematic. But we certainly enter the realm of software design bordering on bikeshedding here. So feel free to cut this short here, and we discuss somewhere else, or never ;)

At the bottom of critique here lies the lock-in of dependencies and strong coupling. I can not take take the serial_node and instantiate it with a different configuration, e.g. moderated to a web-frontend for example. Obviously not the greatest example, but it illustrates the issue. It also means that e.g. writing unit-tests for a increasingly complex piece of software becomes more difficult, forcing us to resort to "dirty tricks" to modify the configuration in place if we wanted to. And sometimes the spider-net-like spread will even prevent these tricks from working, e.g. when an imported module already relies on the configuration to set and start things w/o us having a chance to get in between, and configure things for the test-case. 

I have the following rules about what can go into a module level code:

 - constants. So, like configuration, but immutable. Strictly speaking this is not enforcable by Python, but it's the way I treat them.
 - function or class definitions
 - imports

Only one function (main) is actually invoked when importing a script. That's it. Now of course there are always exceptions to rules, as "A foolish consistency is the hobgoblin of little minds". But I first apply the rules, and then think carefully about exceptions, than the other way round.

To make more concrete examples to the current problem: I would like for rotorhazard to take different configurations via command-line and override certain things via commandline (e.g. the logging setup, because it depends a lot more on the method of invocation, not the base setup - for developing at least. This is currently harder than it should be, because it means I have to run certain amounts of code already during import, and it's only ever getting more.

Ok. My 2 cents :) Hope you can see where I'm coming from, and please do not take this as a war  cry for action of some sort. I'm not the one putting the hours in here.

**Comment by HazardCreative** [comment]
Thanks for spelling that out. I'd be happy to have someone with this kind of depth of knowledge take a crack at refactoring the codebase to the appropriate standards.

@ethomas997 please pull this in if it looks good to you.

**Pull request merged**
