### PR TITLE
Add NuclearHazard files

### PR DESCRIPTION
**Pull request by SpencerGraffunder**
Added:
A folder in resources with all the files and instructions for this design
A build script in the node scripts folder that passes a define to the precompiler that changes the buzzer code
Some code to give the buzzer a PWM signal inside an ifdef

I wish I could do it without the buzzer change but I've ordered multiple buzzers "with driving circuit included" but they never work with a DC input. This change is needed for buzzers that are currently out in the wild. I'm happy to make changes if a cleaner way is suggested.

### CODE REVIEW

**Comment by ethomas997** [comment]
Is there a schematic for the board in the file set?

With the buzzers, what exactly do you mean when you say they don't work.  What buzzers have you tried? (link?)

**Comment by SpencerGraffunder** [comment]
[This](https://github.com/SpencerGraffunder/RotorHazard/blob/NuclearHazardHardware/resources/NuclearHazard/pcb/img/Schematic_NuclearHazard.pdf) is the schematic for the main board.

[This](https://datasheet.lcsc.com/lcsc/2112021630_Jiangsu-Huaneng-Elec-TMB12A03_C96222.pdf) is the buzzer in the latest version. It only makes a small pop noise when given a DC signal. I think there's a slight possibility it's because I forgot to include the series resistor. To meet my design goals, all parts need to be [in stock at JLCPCB](https://jlcpcb.com/parts).

**Comment by ethomas997** [comment]
Can you add a link the schematic to your main README?

For the buzzer, have you tried connecting it directly to output pin on the STM32?

**Comment by HazardCreative** [comment]
Please update following the resolution of the RX read issue.

**Comment by ethomas997** [comment]
@SpencerGraffunder Were you able to get the buzzer to operate correctly?  Is there a change to the schematic / layout needed for that?

**Comment by HazardCreative** [comment]
This is exceptional work to reduce cost and barrier to entry.

**Pull request merged**
