### PR TITLE
Sort pilots by callsign and dont default heat assignments

### PR DESCRIPTION
**Pull request by RogerBFPV**
When creating new  heats, do not just arbitrarily assign the first x pilots. It is better to be 'none' so you can know which slots you have purposely assigned, vs which one remain open.

Also sort all pilot lists by callsign, so that they make better sense in the pulldown lists.

### CODE REVIEW

**Comment by HazardCreative** [comment]
Changing to sort by callsign is insufficient since some groups will want to
sorry by name. This should be selectable and alter the list when changed.

**Comment by RogerBFPV** [comment]
Add a selectable option to sort by pilot name or by callsign.

**Comment by RogerBFPV** [comment]
I've added dynamic pilot attributes.. There is a default attribute that is automatically added labeled 'registered' which reflects if pilots are registered for this race.. These are simple checkbox style attributes..  Race directors can use these for a variety of things like tracking which pilots are registered or which pilots have already paid.. etc.

**Comment by RogerBFPV** [comment]
closing this one, and instead these changes will be in RogerMergedFrom2.0.2 branch that is based off of 2.1 beta 3

**Pull request closed without merging**
