### PR TITLE
Node hardware addressing and ISP reset command

### PR DESCRIPTION
**Pull request by HazardCreative**
Implementing specs in #252 and #262

### CODE REVIEW

**Comment by HazardCreative** [comment]
I could use some help understanding why this compiles fine but fails the build.

**Comment by szafranski** [comment]
Node seems to work with that code. Only issue I have is with serial disabling. If it is disabled by default flashing protocol works 100% every time even with dozen of iterantions over all addresses. With serial enabled it sometimes work and sometimes not. I can try to troubleshoot this until PCB will arrive for testing etc but IMO it is not worth the hustle. I think that it would be better/easier when serial would be disabled by default (maybe with an option to enable ie with some simple pins - shorting for a second). It can be done easily. Second option is to enable serial automatically after few minutes of startup time or something. The state of a situation is like this - code works, but flashing with this code with serial enabled works 50%. With serial disabled - flawlessly every time.

**Comment by ethomas997** [comment]
I believe the unit tests are failing because 'resetNode.cpp' has "#ifndef __TEST__" at the top but 'commands.cpp' does not.  You can try adding that to 'commands.cpp'; I'm not sure if the unit tests will run OK that way or not; it doesn't seem like they use 'commands.cpp'.

**Comment by szafranski** [comment]
It makes sense what you wrote. Tbh coding without need for disabling the serial is much easier - regardless of previous issues. And throubleshooting is and will be much simpler with serial disabled (at least with combination with PCB cause serial as a feature is great) cause avrdude will never output error like “uart busy”. It just throws some random errors like “programmer out of sync” or just don’t want to start at all. We should do something about it. Michael had some idea actually I think?

P.S. And good news - software and PCB are 95% ready.

**Comment by HazardCreative** [comment]
Thanks for the tip on the build. Looks like that led me down the right path to fixing it.

**Comment by szafranski** [comment]
Now everything works as expected

**Pull request merged**
