### PR TITLE
Display options

### PR DESCRIPTION
**Pull request by Klaus-Michael**
I liked the aditional timestamp that you implemented on the race page. However I was missing the Lap ID and I wanted to know the time since the first pass in addition. I implemented both and added a Display Settings section to enable the user to switch them on or off.

### CODE REVIEW

**Comment by HazardCreative** [comment]
I had removed the lap ID intentionally so that the table would take up as little horizontal space as possible, lending to a better mobile display. I think I'll be fine having these as options, though I will probably default them to off.

**Comment by Klaus-Michael** [comment]
Yea I assumed that this was intentional to save screen real estate.
Having it as an option however gives the user the control to adapt it to his space & needs.
Default off is fine for me though.

**Comment by pulquero** [comment]
You could look at the user-agent header to determine if it is mobile or not, and base the defaults on that.

**Comment by HazardCreative** [comment]
I avoid UA sniffing unless absolutely necessary. There are too many ways it can go wrong.

**Comment by HazardCreative** [comment]
Please resolve conflicts so I can pull in.

**Comment by HazardCreative** [comment]
Merged in d5f7ccb

**Pull request closed without merging**
