### PR TITLE
Added LiveTime compatibility.

### PR DESCRIPTION
**Pull request by pulquero**

### CODE REVIEW

**Comment by HazardCreative** [comment]
I really like the direction this is going, handling everything from one server vs. having to switch back and forth when you want livetime compatibility. My only real concern here is that a number of the functions will be changing. Take a look at the frontend-timer branch, which started as a rewrite of the browser timer but is evolving to contain better node filtering and node history output (some of which is still sitting in an unpushed commit on my dev machine, but will go up soon.)

**Comment by BoLtWD** [comment]
I must admit this sounds fantastic.

**Comment by pulquero** [comment]
Looking at the frontend-timer branch, I dont think there will be much conflict. There are only two places where existing code is affected:

1. set_frequency
2. pass_record_callback

In both cases, the alterations are trivial.

**Comment by BoLtWD** [comment]
I would love to see this option pulled

**Comment by BoLtWD** [comment]
pulquero, HazardCreative is this going to be pulled over to the main repository?

**Comment by pulquero** [comment]
Feel free to use my fork while-u-wait https://github.com/pulquero/RotorHazard/tree/ExtRotorHazard. It contains both PRs plus support for split timing.

**Comment by HazardCreative** [comment]
Sure, but there are steps left to be completed before then. This needs resolved against the most recent changes that were merged in. Then I'll be happy to pull it.

**Comment by pulquero** [comment]
Conflict resolved.

**Comment by HazardCreative** [comment]
So the items you mentioned here are all set and this works with the latest updates? https://github.com/RotorHazard/RotorHazard/pull/69#issuecomment-487967083

**Comment by pulquero** [comment]
This is all uptodate, and working.

**Comment by HazardCreative** [comment]
The only thing I'm uncomfortable with is the dummy race format. I see the need, but it feels wrong to have it in a place that is visible to users on the front-end, and especially to specify it by ID, which isn't guaranteed in the database.

I've considered using the RHRace class as the master location for the current race format, and having the change format functions copy the relevant DB data into that. Perhaps that's the right solution for this as well? We could then send the proper rules for Livetime directly into the class, keep them out of the database entirely, and more easily prevent format changing when the system is being driven by LT as a master.

**Comment by pulquero** [comment]
Yep, it is not ideal - something to address in the future? Can the ID be specified in DB.session.add() so we can use a magic value for now?

**Comment by pulquero** [comment]
Slave format is now not in DB.

**Pull request merged**
