### PR TITLE
Scanner improvements and fixes

### LINKED ISSUE #197: RSSI will not register a VTX after using SCANNER
Version: 2.1.0 (dev 3)
Server API: 24
Node API: 21
2.1.0-beta.1

I don`t know if this is an issue, when you goto the scanner page and select SCAN, deselect then go back to Settings - sensor Tuning  the RSSI will not register a VTX for that preset channel. The only way I have found to reset this is by changing all node Frequencies then back to the Frequencies you require, you can then see the RSSI value change when a Quad passes.

### PR DESCRIPTION
**Pull request by pulquero**
Fixes #197 and addresses #156.

### CODE REVIEW

**Comment by ethomas997** [comment]
Re #197, I believe what's happening is that the scanner code is not restoring the original node frequency.  As reported in the issue, if we don't actively reset the node frequency, it can be on the wrong frequency.  I'm still seeing this issue with the current code in this PR.

Other notes:

The scan seems to run quite slowly and take a long time to do a full sweep (using an I2C node).  It does somewhat better running a single node via USB.  (It may need node-code changes to really speed it up.  I have a band scanner on my [ArduVidRx](http://www.etheli.com/ArduVidRx) that does pretty well by stepping through the frequencies on the Arduino side.)

It looks like there's new code in 'settings.html' that will turn off the scanner, but what about other pages (like "Run")?

What if a race is running when the scanner is enabled?  Should the checkboxes be disabled during a race?

The graph size was very small if 8 nodes and zoom level was < 110%.

It'd be good to have an indicator of scan position (after graph filled).

**Comment by ethomas997** [comment]
Also, when I'm running a setup with four I2C nodes and one USB node, and I run the scanner using the USB node (5), it runs alright for a while but then the server starts throwing constant "Interface: Retry (checksum)" errors.  Stopping and starting the server brings it back into a stable state.

**Comment by pulquero** [comment]
OK, it is probably best I add a scan=off and setfreq to every page then - unless we think document unload is reliable enough to add it instead to just the scanner page? I expect the poll rate can be increased, I'm not sure how long you need to sample for at a given freq to avoid any artifacts. I guess it needs a couple of filter window's worth - what poll rate does ArduVidRx use?

**Comment by HazardCreative** [comment]
Changing it back automatically on any page load is problematic. RH doesn't have a single controlling user session; multiple devices could be connected.

Instead, we can test for active scanner mode and launch a pop-up alert (with an option to disable the scanner right in the alert popup) under various conditions:
- page load of Settings or Run
- attempting to Start a race
- attempting to Schedule a race
- a scheduled race has less than 1m before it automatically starts

The popup message system exists, but we might want to extend it so we can restrict these messages only to logged-in admin users.

**Comment by ethomas997** [comment]
@pulquero ArduVidRx waits [35ms](https://github.com/ethomas997/ArduVidRxFirmware/blob/master/Rx5808Fns.h#L42) after changing the frequency.  When it does an RSSI read it samples the analog input 20 times in a row and uses the average.  For a scan, it basically steps through the "known" frequency values (the ones in the table).  With that setup, it's able to do a sweep in 2-3 seconds.  If we're implementing a band-scanner function in the node code, we may want to do similar things.

**Comment by ethomas997** [comment]
The scanner function is still leaving the node on the wrong frequency after completion.  It needs to restore the original frequency for the node.

**Comment by ethomas997** [comment]
When I run it on an 8 node system (with Firefox) it renders eight tiny graphs on one line.

RH_scanner_20200125_1

**Comment by BoLtWD** [comment]
> When I run it on an 8 node system (with Firefox) it renders eight tiny graphs on one line.
> 
> RH_scanner_20200125_1

I reported this    #213

**Comment by ethomas997** [comment]
Regarding restoring the node frequency, I see the [code](https://github.com/RotorHazard/RotorHazard/blob/18271cd4700e29401cb6098e6dff53ae792bf00b/src/server/server.py#L1270) in there doing it.  I think it's working some of the time, but I'm seeing cases where it doesn't.  My best guess is that the heartbeat thread manages to change the node frequency in a race condition (even though it looks like it shouldn't really be possible).

I added some delays and threading, and that seems to address the issue.  See [here](https://github.com/ethomas997/RotorHazard/commit/9be0c58dbfcf31506212c7f42d0013bb5fd27af4).

**Comment by ethomas997** [comment]
The scan speed is still quite slow (at least with I2C nodes).  Polling only the single node could help, and the scan could be made to step through the list of "known" frequencies (~40 channels) only.

A new node command that queries the current RSSI and sets the next scan frequency may improve the speed significantly.

**Comment by pulquero** [comment]
Thanks, I think I might add something like a getRssiAndSetFreq code to the node, and have the interface switch between calling that or READ_LAP_STATS.

**Comment by ethomas997** [comment]
I was thinking it might be best to have a single scanner graph, with a selector to pick which node to read from.  While scanner is running, have the server only poll that hardware node.  Disallow if a race is in progress, and access to scanner page should be admin only.  Also, don't allow a race to start (or show warning) if scanning is in progress.

**Comment by HazardCreative** [comment]
I was thinking about a single graph as well. It would be great to show a static graph to begin with instead of having the dynamic endpoints. I'd also like to see it use the same graphing library as on other pages, for consistency. The Marshal code is a good place to look for how that can be done.

Is there a speed benefit to scanning with multiple nodes or is I2C the bottleneck anyway?

Even if you scan on multiples, the values aren't comparable from one to another. Would work if each were normalized?

As it stands now, each node starts scanning from the low end. Multiple scanning nodes could coordinate and spread out to cover different parts of the spectrum faster.

Perhaps if multiple nodes are used, one could do the "quick" scan on the known channels while others do a complete scan?

This is only marginally related, but if a vertical line could be displayed where a "scanner head" was, that would help in the UI as well. I'm not sure how this is accomplished with this graph library, but if we figured this kind of thing out it would be useful elsewhere. Take a look at the new tuning documentation for an example of how I'd like to highlight lap crossings on the graph if possible.

**Comment by ethomas997** [comment]
I tend to think the variation in response between different hardware nodes would be problematic.  That said, you could try something like subdividing the graph between the nodes, and give each node a section.

**Comment by HazardCreative** [comment]
I don't think that would be workable. It's less likely to have enough data to normalize the signals that way.

**Comment by ethomas997** [comment]
One thing that occurs to me is that we could modify the current implementation to have each graph show 1/4 (or 1/8) of the band, and run them simultaneously.  It'd be interesting to see what that looks like.

**Comment by ethomas997** [comment]
The  '$(document).unload()' call in 'scanner.html' throws an ".unload is not a function" error in the browser console (using Firefox), so that's probably why it's not restoring the node frequency if the page is left while scanning is in progress.  Maybe something more like `$(document).on("unload",...` will work?

**Comment by ethomas997** [comment]
The scanner still needs some work, but merging this in as it's an improvement on what's there.  For now we'll make the band scanner menu item visible only if debug is enabled.

**Pull request merged**
