### PR TITLE
Raspberry Pi mentioned in software setup

### PR DESCRIPTION
**Pull request by szafranski**
According to Casey's reports.

### CODE REVIEW

**Comment by szafranski** [comment]
Now should work

**Comment by ethomas997** [comment]
Unfortunately this PR reverts changes made in https://github.com/RotorHazard/RotorHazard/commit/985aafc211239c8b3aa1d48a8e82e043ae0deedd

If you want I can just add those four lines to SoftwareSetup.md directly with a separate commit.

**Comment by szafranski** [comment]
Do whatever is good for the project :)

**Comment by ethomas997** [comment]
Alright, I added a similar note in commit https://github.com/RotorHazard/RotorHazard/commit/63e688dc8fc1dca00a1cd21c9c1b24bd088c77c4

Thanks for pointing this out.

**Comment by szafranski** [comment]
No problem. I have according question. How translators would know what lines were added to documentation since last translate?

**Comment by ethomas997** [comment]
Don't know that there's a great way; you can look at the history on the 'doc' directory to see recent changes:  https://github.com/RotorHazard/RotorHazard/commits/master/doc

**Comment by szafranski** [comment]
Good point, ok. I think that it will be cool if after some changes devs
will call for new translations and keep track of them. So there won’t be
better and worst translations.

W dniu pon., 23.03.2020 o 03:43 E Thomas <notifications@github.com>
napisał(a):

**Pull request closed without merging**
