### PR TITLE
Add 'Show late laps' option to Current Race page

### PR DESCRIPTION
**Pull request by ethomas997**
Option to allow 'late' laps to be displayed on Current Race page

### CODE REVIEW

**Comment by HazardCreative** [comment]
Should control of this data visibility be kept with the race director?

**Comment by ethomas997** [comment]
> Should control of this data visibility be kept with the race director?

Seems like that would be much more complicated to implement

**Comment by HazardCreative** [comment]
> Seems like that would be much more complicated to implement

Yes, it surely would. But I think it's worth having the discussion to determine if there are reasonable cases where race organizers would not want that data displayed.

**Comment by ethomas997** [comment]
> > Seems like that would be much more complicated to implement
> 
> Yes, it surely would. But I think it's worth having the discussion to determine if there are reasonable cases where race organizers would not want that data displayed.

The data would only be displayed if the person viewing the Current-Race page enables the new 'Show late laps' option.  In our group we have pilots who want to see those lap times.

**Pull request merged**
