### PR TITLE
Multifrequency+stm32

### PR DESCRIPTION
**Pull request by pulquero**

### CODE REVIEW

**Comment by HazardCreative** [comment]
Does this supersede #405, #406, #411, #434?

**Comment by pulquero** [comment]
Yep, merging this should auto-close the other PRs as they share commits.

**Comment by HazardCreative** [comment]
Arduino-based nodes on this branch do not appear visible over I2C and have a solid status LED instead of the expected blink code.

**Comment by pulquero** [comment]
Whoops, forgot to make some base class methods virtual. Added a few more tests, seems to be working now.

**Comment by pulquero** [comment]
Too far out-of-date.

**Pull request closed without merging**
