### PR TITLE
Update german translations

### PR DESCRIPTION
**Pull request by husky-koglhof**

### CODE REVIEW

**Comment by HazardCreative** [comment]
Thanks for this! I'm happy to have the updated translations. However, the timestamp is currently intentionally left out since the Pi is incapable of keeping accurate time on its own when not connected to the internet or an RTC. Once we've built features to make it more reliable (such as being able to copy the time of a connected client) I'll consider re-adding this to the UI again.

**Comment by husky-koglhof** [comment]
Hi, the timestamp change was not planned for the public. So you can ignore this.
I'm currently working on new german translations. I've found, that some text is hardcoded.

**Comment by HazardCreative** [comment]
Where have you found untranslatable strings?

**Comment by husky-koglhof** [comment]
e.g. heats.html
`el.append('<div class="race_class">Unclassified</div>');`
`$('.page-marshal>.panel>.panel-content').html('<p>There is no saved race data available to view.</p>');`

I can search arround all pages, cause I need all pages in german.
Because not all people can speak or translate english in our racegroup https://modellbaufreunde-koglhof.at

**Comment by husky-koglhof** [comment]
sounds strange, but we're using this system for our rc cars and it works great

**Comment by HazardCreative** [comment]
Thanks, I'll make those strings translatable.

**Comment by husky-koglhof** [comment]
I've updated all text and german translations.

**Pull request merged**
