### PR TITLE
bug fix to prevent staging tones when start_delay_max == 0

### PR DESCRIPTION
**Pull request by RogerBFPV**
Our goal is for there to be no staging notes,  only a start tone when we press start race.

There is an intermittent symptom where if we have start_delay min and max == 0  we still sometimes get a single staging tone prior to the start race tone.  

This is very confusing to pilots.. 
The fix is that I check of start_delay_max == 0 then suppress all staging tones.

### CODE REVIEW

**Comment by ethomas997** [comment]
I believe what's happening is that a one-second delay is part of the race staging and it's just enough time to (intermittently) allow a staging beep to be triggered.  In version [2.1.0-beta.1](https://github.com/RotorHazard/RotorHazard/releases/tag/2.1.0-beta.1) this delay is reduced (to 0.9 seconds), which I think should fix the issue.  (See commit [here](https://github.com/RotorHazard/RotorHazard/commit/09f20dce965cd19356124ed4ec9505c3a5d09dda)).

**Comment by RogerBFPV** [comment]
What is interesting is how intermittent the beep problem is.  So the answer was always going to be 1 if mix and max were set to 0.

Yet sometimes it would beep, and sometimes it would not.   This “staging” time was put in for a reason, and if it ever needs to be modified in the future, we will have the beep issue again.  

With my proposed change, it is 100% deterministic of whether to beep or not.

**Comment by ethomas997** [comment]
With the 0.9 second delay that's in there now, the extra beep should never occur, so an extra flag variable is redundant.  I also added a comment saying why the delay value was reduced.

**Comment by HazardCreative** [comment]
Is there a use case for random staging delays without audio feedback? If so, this should be an audio option and not tied to race setup values.

**Comment by RogerBFPV** [comment]
ethomas997:  the 0.9 second change does not solve the problem.  There are conditions by which even when start min and start max are 0, and there is delay between the PI and the browser (such as the PI is very busy calculating round results), I've seen the browser stage 3 seconds which then beeps staging tones prior to start tone on rare occasions which drastically confuses pilots.

HazardCreative: there is no use case for random or fixed staging delays.  The intent is no delay, just sound the start tone when the race director presses start..  If the system happens to lag just a bit before the start tone that is completely acceptable.      
I tell the pilots,  'arm your quads,   go on the tone in less. than 5, and then I press button.   

It is a reasonable configuration to specify Max and Min start delay to 0..  Meaning, no delay and certainly NO staging tone..  There is no need for an additional config option.

**Comment by ethomas997** [comment]
@RogerBFPV Alright, please make this a straightforward single-commit change that we can apply to the current master and we'll merge it.

**Pull request closed without merging**
