### PR TITLE
Mp3 tones spectate

### PR DESCRIPTION
**Pull request by Klaus-Michael**
added the mp3 tone options to the settings page.

The spectate page does not play tones at all at the moment, therefore I didn't add them there at this point in time as the complete beep coded needs to be added first.
Personally I think it would be best to use the same code for spectate and race and to just hide the admin stuff on the spectate page. Otherwise we get a lot of redundant code that needs to be maintained on both sided.

### CODE REVIEW

**Comment by Klaus-Michael** [comment]
just realized that the start tones are played on the spectate page. 
I added the mp3 option. All the crossing sounds however are missing as they are not handled on this page.

**Comment by pulquero** [comment]
I agree it would be nice to merge spectate and race code. We would definitely need to secure the relevant websocket endpoints, so that even if you modified the DOM to show the hidden admin parts, you couldnt do anything useful with them.  Better, if we could just extract out the common code between the two pages with something like callbacks for rendering extra info. Spectate page would just call the common code with empty callbacks. The race page would call the common code with callbacks to render the admin stuff - something like that.

**Comment by HazardCreative** [comment]
@pulquero I could not agree more. Securing the system better is a necessary step forward across the board, not just here. (It's a big reason the JSON API is read-only.) There are other areas that would benefit from common libraries as well. That's been the general direction as I have advanced things forward (such as the visible timer code moving to rotorhazard.js) but there's still work to be done.

**Comment by HazardCreative** [comment]
The settings page also plays tones on crossing enter/exit.

**Pull request merged**
