### PR TITLE
Dynamically load Pi specific libraries with non-Pi fallbacks.

### LINKED ISSUE #7: LED config option not exposed in config file
Config['LED']['LED_STRIP'] uses a define rather than a specific value, which can't be carried in by the parser.

### PR DESCRIPTION
**Pull request by pulquero**
These changes make it possible to run without the LED library, and more than that, run on non-Pi platforms albeit with a mock delta 5 interface layer. This makes development and testing alot easier, and should mean it is possible to write automated tests.

Also fixes #7

### CODE REVIEW

**Comment by pulquero** [comment]
LEDs still work ok, and timing still works on Pi. BTW how do you set the LED_STRIP value in json?

**Comment by HazardCreative** [comment]
I had the same question. :) #7

**Comment by pulquero** [comment]
Ahh. I'll push a commit to fix that then while I'm at it then.

**Comment by ethomas997** [comment]
Looks good to me.

**Pull request merged**
