### PR TITLE
Fix packing of unsigned 8bits.

### LINKED ISSUE #114: raising the exitat value above 127 results in a interface error
When raising the exitat value to 128  or above the value is not saved and an interface error is raised:

Node exit-at set: Node 1 Level 127
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=2 ts=-38416999.1562
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=3 ts=-38416921.8548
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=4 ts=-38416844.4929
Interface: Retry (checksum) limit reached in read_block:  addr=8 offs=50 size=1 retry=5 ts=-38416767.2282
Interface: Value Not Set (1): 114/128/<Node.Node instance at 0x757bcd78>
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=2 ts=-38416536.976
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=3 ts=-38416459.8767
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=4 ts=-38416382.4963
Interface: Retry (checksum) limit reached in read_block:  addr=8 offs=50 size=1 retry=5 ts=-38416305.0248
Interface: Value Not Set (2): 114/128/<Node.Node instance at 0x757bcd78>
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=2 ts=-38416073.756
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=3 ts=-38415996.5385
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=4 ts=-38415919.3457
Interface: Retry (checksum) limit reached in read_block:  addr=8 offs=50 size=1 retry=5 ts=-38415842.4093
Interface: Value Not Set (3): 114/128/<Node.Node instance at 0x757bcd78>
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=2 ts=-38415611.3179
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=3 ts=-38415534.3142
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=4 ts=-38415457.3845
Interface: Retry (checksum) limit reached in read_block:  addr=8 offs=50 size=1 retry=5 ts=-38415380.0908
Interface: Value Not Set (4): 114/128/<Node.Node instance at 0x757bcd78>
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=2 ts=-38415148.911
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=3 ts=-38415071.6819
Interface: Retry (checksum) in read_block:  addr=8 offs=50 size=1 retry=4 ts=-38414991.2551
Interface: Retry (checksum) limit reached in read_block:  addr=8 offs=50 size=1 retry=5 ts=-38414913.9297
Interface: Value Not Set (5): 114/128/<Node.Node instance at 0x757bcd78>
Node exit-at set: Node 1 Level 128

### PR DESCRIPTION
**Pull request by pulquero**
Fixes #114

### CODE REVIEW

**Comment by pulquero** [comment]
I'll test this tomorrow if no-one beats me to it.

**Comment by HazardCreative** [comment]
Can we go one step further with the value check? Though unlikely, users upgrading from earlier versions might have something higher than 255 already stored in the database.

**Comment by pulquero** [comment]
By migrating it in recover_database()?

**Comment by HazardCreative** [comment]
That makes sense. I think it would also make sense to check the constraints on the set function.

**Comment by pulquero** [comment]
Added constraints to the enter/exit setters and db migration.

**Comment by HazardCreative** [comment]
Just realizing now; that kind of check in recover_database needs a check against SERVER_API, otherwise future updates or db corruption will break it.

**Comment by pulquero** [comment]
Isnt that what L3947 does?

**Comment by HazardCreative** [comment]
It's not enough in this case. L3947 initiates the recovery, but doesn't care what versions are moving. Your code will work fine right now when people move from the 1.1 release up to 2.0, but what about down the road when they move to 2.1 or whatever? This is going to run and cut the stored values in half again. recover_database can also be invoked for other database problems like empty heats or race formats. If that happens, this will run and cut the values in half even though the recovery wasn't a migration from one version to another. I think we need a specific check for this exact API level within the recover function.

**Pull request merged**
