### PR TITLE
Use logging module

### PR DESCRIPTION
**Pull request by deets**
This is a no-nonsense conversion to the python logging module. It doesn't really make use of the finer points of the logging setup, but those might be overkill anyway. 

The configuration now allows to specify stderr (default), stdout, syslog or a file. I'm personally excited about the syslog, as I plan on running a service that shows me all of the syslog (tailon for now) on a website. It might even mean one could omit the additional SOCKET_IO if so inclined, to reduce load.

### CODE REVIEW

**Comment by HazardCreative** [comment]
This is great, thank you for contributing! It's a direction we've wanted to go in. There are two things I'd like to see. First, PR #287 has a lot of refactoring, so the work there will definitely need integrated once that goes in very shortly. Second, the log file needs exposed somehow on the front-end so that it can be used for support more easily without having a terminal open (#224).

**Comment by deets** [comment]
I thought that sending these log messages via the SOCKET_IO takes care of presenting them in the frontend? But I'm open to suggestions. Please keep in mind though: I'm not the biggest frontend guy, so concrete steps would help.

My personal plan is to use syslog and tailon as service, so I see *all* system messages. A link in the frontend to that service running on a different port is my current plan.

**Comment by HazardCreative** [comment]
Unless I'm reading it incorrectly, this is only sending messages as they come in. It would be impossible to use that method to get messages that arrived before the browser connected, such as all of the startup logging. This is often the most important information for support.

Is there a command in here to retrieve the entire log so far? I could wire that up to the front-end.

**Comment by deets** [comment]
Ahhh. That's of course no problem, we could easily buffer all incoming messages, and then expose these so you could GET them on demand. Would that solve your issue? Would you want a limit to the number of cached lines, e.g. 10000? Then I would simply use a dequeue.

**Comment by deets** [comment]
I rebased against current master. And added the buffering, not used yet of course, so it is WIP.

I also noticed a quality issue with the new Config.py: it contains tabs. You should really be strict about only allowing 4 spaces and stripping unused space, it makes working with Python and git much better. It's not part of this PR because it should be a concerted effort, possibly even

**Comment by pulquero** [comment]
Instead of buffering, you could just use something like logstash, and kibana for the front-end. Then you can also include syslog easily too.

**Comment by deets** [comment]
While I personally think this is taking canons to hunt squirrels, this is of course possible to set up with this PR, as you can eg. feed syslog into logstash, or consume a logfile.

**Comment by pulquero** [comment]
Logstash/kibana maybe overkill, but I did say something-like. My suggestion was aimed at avoiding having to write and maintain our own log handler/viewer.  This PR addresses the issue from the perspective of a logging framework. Open questions: is there not something suitable to address the other part of the problem? Does the burden of kibana outweigh the burden of roll-your-own-yet-another-not-invented-here log viewer?

**Comment by deets** [comment]
As I mentioned before, my plan is to use https://github.com/gvalkov/tailon to point it at syslog. The log-handler is trivial (as I showed) but I'm the wrong person to make a decision if the burden of adding and configuring a tool like that for the average Joshua is something that the RH project is willing to impose. I can see how adding a page in the current service that just shows the log-contents & copy and paste them for error reporting is not too great a task, but that's just my POV. However the overall beauty of using logging here is that this decision is not necessarily to be made now. It can be deferred as exchanging the sinks for log-messages is easy whilst writing code in the app that uses just the existing log-facilities is un-affected.

**Comment by deets** [comment]
After thinking about this a bit more, I would like to propose a bit of a change to use the system more idiomatically: by doing 

```
import logging
logger = logging.getLogger(__name__)

logger.info("msg %s", `value)
```

we would get a more idiomatic use, with a wider range of options for filtering on demand.

At the same time I feel the "show the log in the website" story is separate. As I've shown it's easy enough to buffer the messages. So I would remove that part, and gladly re-introduce it if asked to.

Any thoughts?

**Comment by HazardCreative** [comment]
I don't have a problem with this. My primary concern is getting #224 resolved so support is easier.

**Comment by deets** [comment]
@HazardCreative please take another look. These are the changes I wanted to make happen. The setup is a bit cleaner now - no custom log interface, just using standard loggers - and we defer logging to greenlets, so it should interfer less with code running out of timers. 

As a next step, I recommend adding a tailon instance and running things through that. A sneak preview is attached. 
tailon

**Comment by deets** [comment]
This is tailon: https://tailon.readthedocs.io/en/latest/ 

We can either run everything through syslog, or have it tail on several logfiles, including a dedicated rotorhazard.log - whatever works better. And it already comes with the ability to download and filter, so less wheels need re-inventing.

**Pull request merged**
