### PR TITLE
Initial Setup of the RotorHazard docs

### PR DESCRIPTION
**Pull request by i-am-grub**
- Makes RH importable without starting server
- Sets up sphinx files for readthedocs
- Configures sphinx to import markdown files

[Current PR Build](https://hazardousgrub.readthedocs.io/en/latest/)

### CODE REVIEW

**Comment by i-am-grub** [comment]
The project maintainers will need to link the project to the [readthedocs ](https://docs.readthedocs.io/en/stable/tutorial/index.html) to activate the automatic builds functionality this pull request is setup to do

**Comment by ethomas997** [comment]
Why does the docs-building setup (in 'doc.conf.py') need to pull in these program directories (and '.py' files)?:
```
sys.path.insert(0, os.path.join(topdir, "src/server"))
sys.path.insert(0, os.path.join(topdir, "src/server/util"))
sys.path.insert(0, os.path.join(topdir, "src/interface"))
```

**Comment by i-am-grub** [comment]
Sphinx has the ability to pull information from the project when building the documentation for building API information, or just including information from the code itself.

On [another branch](https://github.com/i-am-grub/HazardousGrub/blob/auto-api/src/server/RHAPI.py), I'm working on transitioning the RHAPI.md into docstrings within the code. The [result](https://hazardousgrub.readthedocs.io/en/auto-api/api.html) allows for self documenting code by importing the RH project. 

Another example is for pulling constants directly from the RH server from the import. One of the things I do in the Toolkit's documentation is have a link that automatically updates based off the contents of the manifest.json file. 
image

The reason the os.path.join is needed is because the docs are built with the doc folder as the working directory, so the paths need to be added to path when importing the server.

**Comment by ethomas997** [comment]
I do like the idea of having the server-startup code only execute when it's running as "__main__"; I may just go ahead and implement that as separate commits.  Is it possible to put those new doc-building files ("Makefile", etc) in a "doc/readthedocs" subdirectory?

**Comment by i-am-grub** [comment]
Yes, the read the docs files can be moved. The only thing that is location dependent is the .readthedocs.yaml file in the root directory

**Comment by i-am-grub** [comment]
After some testing, I was unable to move the files to a sub-directory of the docs folder. It appears the sphinx is built to operate from the root directory of the docs folder.

**Comment by ethomas997** [comment]
@i-am-grub With PR #935 I think I've gotten the 'server.py' code to where it can be imported without starting the server.  Are you still looking to do something with sphinx/readthedocs?

**Comment by i-am-grub** [comment]
@ethomas997 Yeah, I'm still looking to set something up eventually. I'm probably going to close this PR start over on a new branch with that PR included. There's been a few things I've picked up since opening up this one.

**Pull request closed without merging**
