### PR TITLE
Low-pass filter

### PR DESCRIPTION
**Pull request by pulquero**
You can choose the filter in rssi.cpp.

### CODE REVIEW

**Comment by HazardCreative** [comment]
I'm getting warning messages, but it does compile.

Ran a test with two nodes set to LPF and two set to Median, all on the same frequency.
This LPF node's realtime didn't line up very well with its recalc. (Lap 3=967ms, 5=2916ms)
image

The second LPF node did better, but some were still off by a fair amount. (Lap 6=409ms, 7=3262ms)
image

Median node recalcs were all within 2ms and usually no more than 1ms.
image
image

*Before* marshaling/recalculating all nodes:
Disagreement between LPF and Median (average of both nodes of type):
Min: 37ms, Max: 3321ms, Med: 81ms, Avg: 446ms

*After* marshaling/recalculating all nodes:
LPF on left, Median on right.
image

Lap time disagreements:
LPF nodes: Min: 9ms, Max: 1113ms, Med: 135ms, Avg: 303ms
Median nodes: Min: 16ms, Max: 294ms, Med: 136ms, Avg: 136ms
Between LPF and Median (average of both nodes of type):
Min: 56ms, Max: 293ms, Med: 121ms, Avg: 148ms

Disagreements before/after marshaling (corrected for lap counts, average of both nodes of type)
LPF node disagreements: Min: 0ms, Max: 3214ms, Med: 1ms, Avg: 419ms
Median node disagreements: Min: 0ms, Max: 2ms, Med: 0ms, Avg: 0ms

This is just one sample and variance in nodes likely affect the results.

**Comment by pulquero** [comment]
Converted more structs to classes and abstracted the send buffer. I should be able to add support for a send buffer that stores more history.

**Comment by pulquero** [comment]
We now have a 10-history send buffer and a 100hz lpf.

**Comment by HazardCreative** [comment]
Ran some quick tests. Used two nodes on median as control and two nodes on LPF.

100Hz LPF:
Calibration was very tight. Times could be marshaled out but incoming data was not as clean. Signal would bounce around quite a bit, picking up a lot of extra very short laps. This is definitely not an improvement.

image

20Hz LPF:
Worked pretty well. Calibration is tighter but this could be hardware. Recalculated results did not always perfectly match realtime results. More testing is needed, but history should be reviewed as this should match when the same calibration values are used.

**Comment by pulquero** [comment]
One possibility is that the send buffer doesn't have enough capacity at 20hz.

**Comment by pulquero** [comment]
I finally worked up the energy to rebase this. I've set the filter to median, so it is easy to test that this behaves identically to the current code. It can then be merged, and different filters experimented with later.

**Comment by HazardCreative** [comment]
Ran some tests with this. The behavior appeared identical and any data difference between nodes looked within hardware tolerance.

**Pull request merged**
