### PR TITLE
LiveTime improvements

### LINKED ISSUE #307: LiveTime Integration
It would be nice to have a way to adjust the node settings from within LiveTime ... I think I understand the rotorhazard goes into slave mode after LiveTime connects on port :5000
Any thoughts on this ???

### PR DESCRIPTION
**Pull request by HazardCreative**
* Add dedicated settings page for LiveTime
Closes #307

### CODE REVIEW

**Comment by ErikBorra** [comment]
Livetime is an event management system. It expects a connected device to be a tracker that just says: this frequency has crossed at this timestamp. That seems to work fine with this pull request.

Tuning, however, cannot be done in Livetime yet. To have Livetime work with Rotorhazard, one needs to choose Delta 5 as the tracker. While node frequencies can be synced from Livetime to RH, Livetime has hardcoded the following settings: calibration threshold, calibration offset, and trigger threshold. These settings are from Delta 5 and have become obsolete in RH. Ideally, Livetime would thus add RotorHazard as a tracker and allow to change node frequencies, as well as tuning parameters EnterAt and ExitAt.

Dreaming on... Rather than manually setting EnterAt and ExitAt values, I find the true strength of RH in its marshall page. In order to use the marshall function, however, RH expects data from a race that was started, stopped and saved via the RH interface. Moreover, RH will complain if a race was started without pilots assigned to a heat. If you want to use Livetime in combination with the marshall page, you now thus need to replicate a big part of Livetime's event management, such as pilot registration and heat allotment. At least in the first few rounds, when tuning. And possibly also later, when nodes start to drift. (Adaptive calibration cannot be used if there is no saved race data in RH.)

In order to use the marshall functionality with livetime, I suggest the following. Each time Livetime starts a race, it sends a start signal to the tracker (it already does). Upon receiving this signal, RH should start a new race within RH (with the node frequencies set via Livetime's decoder settings and using frequencies as pilot names). Races should be stopped and saved in the RH database on the next start. (Livetime does not, and will not, send a stop signal.) Once there are saved races, the marshall page can be used to further tune the nodes. (Although recalculated laps will not propagate to Livetime.) The added benefit is that adaptive calibration will actually work too.

Unrelatedly, when testing Livetime I observed a difference in how Livetime and RH recalculate laps. The marshall page allows for recalculating lap times by updating EnterAt and ExitAt values. The lap timems make sense because of their visual correspondence in the RSSI graph. Livetime does not have such a graph as it does not get RSSI data. It just gets a frequency and a timestamp for each crossing. When deleting a lap in Livetime, the crossing times after that lap are recalculated. These often seem incorrect, and there is no way of verifying them with RSSI graphs. Again, marshalling in RH rocks. It would rock even more if marshalling could be done on live data, as per issue #365 

I also found that the audio section is not necessary on the /decoder page, see issue #364

**Comment by HazardCreative** [comment]
I believe LiveTime's expectation is that tuning will be done on the /decoder page. They will provide a link to launch it in a window.

The empty heat warning should be suppressed when LT calls for a race start. That probably warrants opening a new issue.

As noted on #365, marshaling a race that is still running is very difficult. It gets much simpler if the race can be stopped first.

Adaptive calibration will not be possible with LiveTime until LT provides race and pilot data back to RH. Tying calibration to individual pilots is the most important part of that system. Understanding the class scheme also helps significantly.

The RSSI data LT receives is the realtime data; it does not read the high-precision history data that RH uses to recalculate with.

**Comment by ErikBorra** [comment]
Tuning on /decoder page is fine, but then Livetime should allow setting node frequencies *and* EnterAt and ExitAt. D5 settings should be removed. Ideally Livetime would also provide access to the live marshalling function as suggested in #365
 ;)

I did not know adaptive calibration was tied to pilots, rather than frequencies. Where can I find some more information about the rationale for this? 

While Livetime can send pilot and class data to its accompanying Racevision software, it will not send such data to a tracker or other software. While a few years ago such data was available through a socket with clear text json, they have now encrypted that data stream and do not seem to want to provide such access to other software. That said, there could be a workaround by using the data in a race's streaming overlays accessible via livefpv.com. It is however unlikely that Livetime will endorse the workaround.

**Comment by ethomas997** [comment]
There's a bit of doc on Adaptive Calibration here:  https://github.com/RotorHazard/RotorHazard/blob/master/doc/Tuning%20Parameters.md#calibration-mode

The idea is that if a previous heat had the same pilot on the same node (and frequency) then those previous EnterAt/ExitAt value are reused.

**Comment by ErikBorra** [comment]
@ethomas997 I get what it does. Not why it does so. Why is this not tied to just frequency? Did you notice so much difference between pilots in a race, even when everybody has a ce approved vtx and transmits on max 25mw? Also, during a race a pilot will typically fly with two or three different quads.

**Comment by HazardCreative** [comment]
> Did you notice so much difference between pilots in a race, even when everybody has a ce approved vtx and transmits on max 25mw? Also, during a race a pilot will typically fly with two or three different quads.

Differences between pilots on the same channel is the reason the feature was asked and developed for.

Not every race event is carefully controlled with VTx approvals and power measurements. Many smaller groups don't go to these lengths. AC helps with that—but some seasoned race directors still asked for the feature.

Adaptive calibration also takes into account race classes, since equipment is more likely to change for all pilots at once. For example, open vs. spec classes, or 5" vs 3" classes. AC will return to the known-good values should an organizer decide to intermingle races from each class instead of running them serially.

**Comment by ErikBorra** [comment]
Interesting. I've run plenty of races where we indeed asked for a good vtx (not everybody did) and required everyone to be on the same output power (typically 25mw). Hardly ever needed to retune the LapRF during a race, hence my question.

I did notice that after a few heats, I had to retune RotorHazard nodes for most pilots. Typically to lower EnterAt and ExitAt values. What is the cause of this and would adaptive calibration help with it?

**Comment by HazardCreative** [comment]
These timers are often built with the first-available hardware. At least one google module manufacturer is sitting on *thousands* of RX5808 modules because they didn't pass strict sensitivity thresholds in QA; and the ratio of pass/fail was near 50%. I don't know what the LapRF is doing exactly to get their very good crossing sensitivity, (at least with analog,) but I do suspect hardware to be involved. (If there's more that can be done in software, I'm listening. I don't have any real background in RF or DSP and welcome suggestions.)

RX5808 modules change in sensitivity with heat. I often plug in my timer as soon as I arrive at the venue and let it come up to a stable operating temp before running practices and doing any tuning.

**Pull request merged**
