### PR TITLE
Support for INA219 devices.

### PR DESCRIPTION
**Pull request by pulquero**

### CODE REVIEW

**Comment by BoLtWD** [comment]
This make a very simple solution and easy to implement, I take it adding alongside the BME280 on i2c is not going to be a problem?

**Comment by pulquero** [comment]
No problems, I currently have one bme280, one ina219 near the pi, and another ina219 for lipo voltage.

**Comment by BoLtWD** [comment]
When implemented it would be nice to have a volts alarm so the user can define a low voltage and have a warning of some kind POP up, Audio or both.

**Comment by pulquero** [comment]
Estimated battery time remaining would be very useful.

**Comment by HazardCreative** [comment]
What are your thoughts on this vs. #88?

**Comment by BoLtWD** [comment]
I must admit I like the simplicity of this also you get voltage, current and power. As the range is  0 V to +26 V this would give you a range that would be up to a 6s battery depending on the Pololu voltage regulators. This also keeps it modulator fitting alongside the BME280.

**Comment by BoLtWD** [comment]
The only other factor to consider is any difference between the accuracy/resolution and if the difference is a concern.

**Comment by pulquero** [comment]
INA219 has a 12-bit ADC, nano has a 10-bit ADC.

**Comment by Ryanf55** [comment]
Just set up my timer today to test the voltage divider code but I saw this. I think either solution is a good one.

Yea, 10 bit resolution is not great, but it's not bad either for the purposes of determining if a battery is dead. A calibration factor could be programmed in so you don't need 1% resistors. 

If determining battery remaining, there would need to be a config for the battery capacity. Even then, you can't assume the battery is fully charged or that the user configured the battery correctly. Thus, I do not believe current sensing is particularly useful. 

Because the battery voltage changes slowly, why not just poll the node for voltage between heats?

**Comment by pulquero** [comment]
Some of the points you make are equally valid for  current sensoring in betaflight. So I feel battery capacity estimation should be just as good as that, and probably better since the current draw is more stable.

**Comment by Ryanf55** [comment]
Yep. 

Not sure if this is the right place, but if we want to also support the[ ADS1115 and ADS1015 sensors](https://learn.adafruit.com/raspberry-pi-analog-to-digital-converters/ads1015-slash-ads1115), I wrote a class to support them easily.
See it here: https://github.com/Ryanf55/ads1x15

They also run on I2C. While they only support voltage, the ADS1115 has a 12 bit resolution. 

Another nice thing is they have 4 channels which would be useful if multiple batteries were used on a skottchy diode for hot-swapping batteries on the node ( I plan to do this and sense both connected batteries). 

I'd love to help implement the ADS sensor in the Rotorhazard code base, but even with pulquero's commit to review, it's a bit over my head. 

The ADS class I made should make it pretty easy to add support, aside from needing to add more spots in the display for multiple voltages. If anyone wants to add support in code, I'll do the documentation.

**Comment by pulquero** [comment]
I'm happy to do it, don't know if you want to try first? I suspect the tricky part is the dynamic loading of the module, so if you want to write it 'normally', I'll add that part afterwards?

**Comment by pulquero** [comment]
I might look at a plugin system for sensors at some stage, then the sensor plugins themselves wouldn't have to worry about doing any dynamic loading.

**Comment by Ryanf55** [comment]
I'll give it a go. Just submitted pull request #109 .

Dynamic loading wasn't too bad because I had the ads1x15 module handle checking if a device existed in __init__ using smbus.

I had to copy the ads1x15 in to the RotorHazard/src/server to get it to import. 

Where do you view the data in the web interface?

**Pull request merged**
