### PR TITLE
interim solution for issue #46

### PR DESCRIPTION
**Pull request by Klaus-Michael**
Not a permanent solution, just a quick extention of the current front-end timer to enable voice callouts if the delay to the race starts is above 5s.
It can be turned on and off. Current default is on.

### CODE REVIEW

**Comment by HazardCreative** [comment]
I'm still concerned about encouraging long staging times before there's a fix in place for #13.

**Comment by Klaus-Michael** [comment]
Thats definitly a problem. However with the current code logn statign times are the only way to enable the "Race Director" to participate in a race or to fly alone and have a start on the start tone.
Having 20s beeps simply does not work for me and is quied annoying as well ;-)

So as long as there is no separate timer I think this is a acceptable workaround.

**Comment by HazardCreative** [comment]
The new timing code much more easily allows implementing this functionality without the downfalls as in #13. Take a look in the https://github.com/RotorHazard/RotorHazard/tree/frontend-timer branch, which is being tested/prepared to merge into master.

**Comment by HazardCreative** [comment]
Closing because this is no longer needed with the new scheduler in place. Thanks for the temporary solution for those who wanted it before this was ready.

**Pull request closed without merging**
