### PR TITLE
Plugin support for generating heat slots seeded by class rank

### PR DESCRIPTION
**Pull request by skyfpv**
This PR allows plugin developers to generate heat slots which are seeded by class rank using the heat generator. This gives them the same functionality which can currently only be done via the UI, but now it can be done programmatically with a plugin.

### CODE REVIEW

**Comment by HazardCreative** [comment]
Thanks! I've wanted to do this and it should be an easy pull. 
I assume you have a test case—can you link it?

**Comment by skyfpv** [comment]
I haven't written any unit tests if that's what you mean. I did test it manually using the the [Street League plugin](https://github.com/skyfpv/streetleague_rotorhazard_plugin.git) I've been working on. If that's what you're talking about, you can also verify it works with that plugin.

**Comment by skyfpv** [comment]
I'm looking into the unit tests (I'm a bit new to unit testing in general). I'll see if I can whip something up, unless you beat me to it. I'm it should be a heat generator test in general? It doesn't look like there are any heat generation tests yet.

**Comment by HazardCreative** [comment]
Unit tests would be super, but what I was looking for was something like the plugin you linked. Thanks!

**Pull request merged**
