### PR TITLE
updated translation - Polish

### PR DESCRIPTION
**Pull request by szafranski**
mainly in json and few minor changes in doc folder

### CODE REVIEW

**Comment by szafranski** [comment]
I haven been able to translate elements visible on the imaga attached. Will be happy to add it later if possible.
translation

**Comment by szafranski** [comment]
I deleted files that I wasn't intending to change from the request.

**Comment by HazardCreative** [comment]
This PR needs a little bit of work before we can pull it in. Deleting files signals that these files should also be deleted in the main project when the PR is pulled in. To avoid changes on the main project messing with your PR, you'll want to make a branch specific to the change you are making and do the PR from there. Something like "pl-language-update" would be perfect.

https://github.com/RotorHazard/RotorHazard/blob/master/doc/Development.md

Also, at least for now, don't change the links in the files to point to the same-language versions (like you have in pl-Hardware Setup.md). We might be able to change this in the future, but for now this breaks the offline document reader.

**Comment by szafranski** [comment]
The file name changes were unintended - I redo them in next commit. I might mess up some things. I will open another PR from new for. Thanks

**Pull request closed without merging**
