### PR TITLE
Update language.json

### PR DESCRIPTION
**Pull request by MoonKIE666**
New translation into Spanish, with all the data that appears in version 4.0.0-Beta 5

### CODE REVIEW

**Comment by MoonKIE666** [comment]
Repare mistakes in translation to Spanish and add more

**Comment by HazardCreative** [comment]
Thank you! I seem some strings from the bundled plugins don't have translations yet, are you able to do that as well?

image

**Comment by MoonKIE666** [comment]
> Thank you! Are you able to cover these parts as well?
> 
> image
> 
> image

I already did it in the language.json file but I don't know why those parts are not translated.  I don't have much idea about coding.  But I think that is part of some file or web style that cannot be changed with language.json

**Comment by HazardCreative** [comment]
Hmm... I'll take a look. Might not be on your end at all.

**Comment by HazardCreative** [comment]
Please pull changes and let me know if anything is still missing.

**Comment by MoonKIE666** [comment]
image

Hi Michael, I don't know what happens with these two sections of the chrono, but they are not translated with the language.json file

I have translated all those words in the language.json file but they still do not appear translated when I run the tests in my chrono.

**Comment by MoonKIE666** [comment]
imagen

It looks better, but there are some things that weren't translated before you made these last changes. I will write again and tell you as soon as possible

**Comment by MoonKIE666** [comment]
imagen

I have uploaded your changes and I have rewritten things that I left unwritten, but I see that there are still some things that do not translate inside the "Ranking"="Ranking" drawer. These three conditions for the ranking that I have pointed out to you continue to appear in English, although they are translated in the language.json file

**Comment by HazardCreative** [comment]
Fixed. Any other areas?

**Comment by MoonKIE666** [comment]
imagen

Oops, I didn't tell you any of this, because I thought it was part of a separate field in which each person could change the name of the race format. But I think it should also be translated. The translations are uploaded to language.json

With this, I think it would be there.

**Comment by HazardCreative** [comment]
> ... I thought it was part of a separate field in which each person could change the name of the race format. But I think it should also be translated.

I don't want to run user-supplied content through translation—but if you reset the formats list, the defaults are generated using translated strings.

There are a couple updates needed among the default format translations.

**Comment by HazardCreative** [comment]
Time to launch 4.0, further changes will need to go into a new PR.

**Comment by MoonKIE666** [comment]
Don't worry, that part isn't very important either. In fact, it is well understood in English for anyone who speaks Spanish. Besides, if you like a race format, you can leave it configured the same and just change the name to Spanish to remember you, as we have done with the "Carrera de la Lligueta"

**Pull request merged**
